import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "آکادمی برنامه نویسی کودکان | صفحه اصلی",
  description: "Generated by create next app with Shahin",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="">{children}</body>
    </html>
  );
}


